# Generated by Django 4.2.20 on 2026-01-16 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RobotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=32, unique=True, verbose_name="组Key"),
                ),
                ("name", models.CharField(max_length=64, verbose_name="组名称")),
                (
                    "expected_total",
                    models.PositiveIntegerField(default=0, verbose_name="预期数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "机器人组",
                "verbose_name_plural": "机器人组",
                "db_table": "robot_groups",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="RobotComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "robot_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="机器人ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="名称"
                    ),
                ),
                (
                    "part_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="部件编号"
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="参考编号"
                    ),
                ),
                ("type_spec", models.CharField(max_length=128, verbose_name="类型")),
                ("tech", models.CharField(max_length=128, verbose_name="工艺")),
                ("mark", models.IntegerField(default=0, verbose_name="标记")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("checks", models.JSONField(default=dict, verbose_name="A1-A7检查项")),
                (
                    "level",
                    models.CharField(
                        choices=[("H", "H"), ("M", "M"), ("L", "L")],
                        default="L",
                        max_length=1,
                        verbose_name="等级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("maintenance", "维护中"),
                        ],
                        default="online",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "battery",
                    models.PositiveSmallIntegerField(default=100, verbose_name="电量"),
                ),
                (
                    "health",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="健康度"
                    ),
                ),
                (
                    "motor_temp",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="电机温度"
                    ),
                ),
                (
                    "network_latency",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="网络时延"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近上报"
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="风险分数"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "严重"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        default="low",
                        max_length=16,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_history",
                    models.JSONField(default=list, verbose_name="历史风险记录"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="robots.robotgroup",
                        verbose_name="组",
                    ),
                ),
            ],
            options={
                "verbose_name": "机器人部件",
                "verbose_name_plural": "机器人部件",
                "db_table": "robot_components",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "robot_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="机器人ID"
                    ),
                ),
                (
                    "robot_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="机器人名称",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="事件信息")),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="原因"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "严重"),
                            ("high", "高"),
                            ("medium", "中"),
                            ("low", "低"),
                        ],
                        default="low",
                        max_length=16,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="风险分数"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                ("triggered_at", models.DateTimeField(verbose_name="触发时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_events",
                        to="robots.robotcomponent",
                        verbose_name="关联部件",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_events",
                        to="robots.robotgroup",
                        verbose_name="组",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险事件",
                "verbose_name_plural": "风险事件",
                "db_table": "risk_events",
                "ordering": ["-triggered_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(
                fields=["robot_id"], name="robot_compo_robot_i_5d8404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(
                fields=["part_no"], name="robot_compo_part_no_601d23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(
                fields=["reference_no"], name="robot_compo_referen_80a7e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(
                fields=["risk_level"], name="robot_compo_risk_le_7122b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(fields=["level"], name="robot_compo_level_8964df_idx"),
        ),
        migrations.AddIndex(
            model_name="robotcomponent",
            index=models.Index(fields=["status"], name="robot_compo_status_873973_idx"),
        ),
        migrations.AddIndex(
            model_name="riskevent",
            index=models.Index(
                fields=["robot_id"], name="risk_events_robot_i_139081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskevent",
            index=models.Index(
                fields=["severity"], name="risk_events_severit_37ab5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskevent",
            index=models.Index(fields=["status"], name="risk_events_status_6bff1f_idx"),
        ),
        migrations.AddIndex(
            model_name="riskevent",
            index=models.Index(
                fields=["triggered_at"], name="risk_events_trigger_23739b_idx"
            ),
        ),
    ]
