# Generated by Django 4.2.20 on 2026-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotcomponent",
            name="number",
            field=models.IntegerField(default=0, verbose_name="Number"),
        ),
    ]
