# Generated by Django 6.0.1 on 2026-01-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("temperature", "温度"),
                            ("humidity", "湿度"),
                            ("pressure", "气压"),
                            ("light_intensity", "光照强度"),
                            ("pm25", "PM2.5"),
                            ("pm10", "PM10"),
                            ("co2", "CO2"),
                            ("voc", "VOC"),
                            ("o3", "O3"),
                            ("noise_level", "噪音"),
                            ("battery_level", "电池电量"),
                            ("signal_strength", "信号强度"),
                        ],
                        max_length=20,
                        verbose_name="传感器类型",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                            ("equal", "等于"),
                            ("not_equal", "不等于"),
                            ("between", "介于之间"),
                            ("outside", "超出范围"),
                        ],
                        max_length=20,
                        verbose_name="条件",
                    ),
                ),
                (
                    "threshold_min",
                    models.FloatField(blank=True, null=True, verbose_name="最小阈值"),
                ),
                (
                    "threshold_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大阈值"),
                ),
                (
                    "threshold",
                    models.FloatField(blank=True, null=True, verbose_name="阈值"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "cooldown_minutes",
                    models.IntegerField(default=5, verbose_name="冷却时间(分钟)"),
                ),
                (
                    "repeat_alert",
                    models.BooleanField(default=False, verbose_name="重复报警"),
                ),
                (
                    "repeat_interval_minutes",
                    models.IntegerField(default=30, verbose_name="重复间隔(分钟)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "报警规则",
                "verbose_name_plural": "报警规则",
                "db_table": "alert_rules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                            ("false_alarm", "误报"),
                            ("auto_resolved", "自动解决"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("message", models.TextField(verbose_name="报警消息")),
                ("current_value", models.FloatField(verbose_name="当前值")),
                ("severity", models.CharField(max_length=20, verbose_name="严重程度")),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="触发时间"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "recovery_value",
                    models.FloatField(blank=True, null=True, verbose_name="恢复值"),
                ),
                (
                    "recovery_time",
                    models.DurationField(
                        blank=True, null=True, verbose_name="恢复耗时"
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(default=False, verbose_name="通知已发送"),
                ),
                (
                    "notification_count",
                    models.IntegerField(default=0, verbose_name="通知次数"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_records",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解决人",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="alerts.alertrule",
                        verbose_name="报警规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "报警记录",
                "verbose_name_plural": "报警记录",
                "db_table": "alert_records",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "邮件"),
                            ("sms", "短信"),
                            ("webhook", "Webhook"),
                            ("wechat", "微信"),
                            ("dingtalk", "钉钉"),
                            ("feishu", "飞书"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("config", models.JSONField(default=dict, verbose_name="配置信息")),
                (
                    "min_severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="最低严重程度",
                    ),
                ),
                (
                    "notify_24h",
                    models.BooleanField(default=True, verbose_name="24小时通知"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="免打扰开始时间"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="免打扰结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知配置",
                "verbose_name_plural": "通知配置",
                "db_table": "notification_configs",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("retrying", "重试中"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("recipient", models.CharField(max_length=255, verbose_name="接收人")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "alert_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="alerts.alertrecord",
                        verbose_name="报警记录",
                    ),
                ),
                (
                    "notification_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="alerts.notificationconfig",
                        verbose_name="通知配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知日志",
                "verbose_name_plural": "通知日志",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["device", "enabled"], name="alert_rules_device__6c36a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecord",
            index=models.Index(
                fields=["device", "-triggered_at"],
                name="alert_recor_device__cabd19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecord",
            index=models.Index(
                fields=["status", "-triggered_at"], name="alert_recor_status_ed12a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecord",
            index=models.Index(
                fields=["severity", "-triggered_at"],
                name="alert_recor_severit_d7daf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["alert_record", "status"], name="notificatio_alert_r_8e9aaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["notification_config", "-created_at"],
                name="notificatio_notific_5a9339_idx",
            ),
        ),
    ]
