# Generated by Django 6.0.1 on 2026-01-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                (
                    "device_id",
                    models.CharField(max_length=50, unique=True, verbose_name="设备ID"),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("temperature", "温度传感器"),
                            ("humidity", "湿度传感器"),
                            ("light", "光照传感器"),
                            ("pm25", "PM2.5传感器"),
                            ("co2", "CO2传感器"),
                            ("composite", "综合传感器"),
                        ],
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="安装位置")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("maintenance", "维护中"),
                            ("error", "故障"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="设备状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="设备描述")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="MAC地址"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="固件版本"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="制造商"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="型号"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="序列号"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="海拔(米)"),
                ),
                (
                    "install_date",
                    models.DateField(blank=True, null=True, verbose_name="安装日期"),
                ),
                (
                    "warranty_date",
                    models.DateField(blank=True, null=True, verbose_name="保修期至"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后活跃时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collect_interval",
                    models.IntegerField(default=60, verbose_name="采集间隔(秒)"),
                ),
                (
                    "enable_alert",
                    models.BooleanField(default=True, verbose_name="启用报警"),
                ),
                (
                    "data_retention_days",
                    models.IntegerField(default=90, verbose_name="数据保留天数"),
                ),
                (
                    "auto_cleanup",
                    models.BooleanField(default=False, verbose_name="自动清理过期数据"),
                ),
                (
                    "extra_config",
                    models.JSONField(blank=True, default=dict, verbose_name="额外配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备配置",
                "verbose_name_plural": "设备配置",
                "db_table": "device_configs",
            },
        ),
        migrations.CreateModel(
            name="DeviceMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "例行维护"),
                            ("repair", "故障维修"),
                            ("upgrade", "固件升级"),
                            ("calibration", "校准"),
                            ("replacement", "更换部件"),
                        ],
                        max_length=20,
                        verbose_name="维护类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="维护描述")),
                ("scheduled_date", models.DateTimeField(verbose_name="计划时间")),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "已计划"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="费用",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="技术人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备维护记录",
                "verbose_name_plural": "设备维护记录",
                "db_table": "device_maintenance",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["device_id"], name="devices_device__c4b5e4_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_status_9f14cf_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type"], name="devices_device__f7aa79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["owner"], name="devices_owner_i_508ed1_idx"),
        ),
    ]
