# Generated by Django 6.0.1 on 2026-01-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("excel", "Excel"), ("csv", "CSV"), ("json", "JSON")],
                        max_length=10,
                        verbose_name="导出类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(blank=True, null=True, verbose_name="数据行数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_records",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据导出记录",
                "verbose_name_plural": "数据导出记录",
                "db_table": "data_exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("hour", "小时"),
                            ("day", "天"),
                            ("week", "周"),
                            ("month", "月"),
                        ],
                        max_length=10,
                        verbose_name="汇总类型",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("temp_avg", models.FloatField(null=True, verbose_name="平均温度")),
                ("temp_max", models.FloatField(null=True, verbose_name="最高温度")),
                ("temp_min", models.FloatField(null=True, verbose_name="最低温度")),
                ("humidity_avg", models.FloatField(null=True, verbose_name="平均湿度")),
                ("humidity_max", models.FloatField(null=True, verbose_name="最高湿度")),
                ("humidity_min", models.FloatField(null=True, verbose_name="最低湿度")),
                ("pm25_avg", models.FloatField(null=True, verbose_name="平均PM2.5")),
                ("pm25_max", models.FloatField(null=True, verbose_name="最高PM2.5")),
                ("co2_avg", models.FloatField(null=True, verbose_name="平均CO2")),
                ("co2_max", models.FloatField(null=True, verbose_name="最高CO2")),
                (
                    "data_count",
                    models.IntegerField(default=0, verbose_name="数据点数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_summaries",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据汇总",
                "verbose_name_plural": "数据汇总",
                "db_table": "data_summaries",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["device", "summary_type", "-start_time"],
                        name="data_summar_device__930024_idx",
                    )
                ],
                "unique_together": {("device", "summary_type", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, null=True, verbose_name="温度(℃)"),
                ),
                (
                    "humidity",
                    models.FloatField(blank=True, null=True, verbose_name="湿度(%)"),
                ),
                (
                    "pressure",
                    models.FloatField(blank=True, null=True, verbose_name="气压(hPa)"),
                ),
                (
                    "light_intensity",
                    models.FloatField(
                        blank=True, null=True, verbose_name="光照强度(lux)"
                    ),
                ),
                (
                    "uv_index",
                    models.FloatField(blank=True, null=True, verbose_name="紫外线指数"),
                ),
                (
                    "pm25",
                    models.FloatField(
                        blank=True, null=True, verbose_name="PM2.5(μg/m³)"
                    ),
                ),
                (
                    "pm10",
                    models.FloatField(
                        blank=True, null=True, verbose_name="PM10(μg/m³)"
                    ),
                ),
                (
                    "co2",
                    models.FloatField(
                        blank=True, null=True, verbose_name="CO2浓度(ppm)"
                    ),
                ),
                (
                    "voc",
                    models.FloatField(
                        blank=True, null=True, verbose_name="VOC浓度(ppb)"
                    ),
                ),
                (
                    "o3",
                    models.FloatField(
                        blank=True, null=True, verbose_name="O3浓度(ppb)"
                    ),
                ),
                (
                    "noise_level",
                    models.FloatField(
                        blank=True, null=True, verbose_name="噪音水平(dB)"
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(blank=True, null=True, verbose_name="风速(m/s)"),
                ),
                (
                    "wind_direction",
                    models.FloatField(blank=True, null=True, verbose_name="风向(度)"),
                ),
                (
                    "rainfall",
                    models.FloatField(blank=True, null=True, verbose_name="降雨量(mm)"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="采集时间"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="数据是否有效"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="电池电量(%)"
                    ),
                ),
                (
                    "signal_strength",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="信号强度(dBm)"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器数据",
                "verbose_name_plural": "传感器数据",
                "db_table": "sensor_data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "-timestamp"],
                        name="sensor_data_device__aa8879_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="sensor_data_timesta_97a1d1_idx"
                    ),
                    models.Index(
                        fields=["is_valid"], name="sensor_data_is_vali_bf82dd_idx"
                    ),
                ],
            },
        ),
    ]
