# Generated by Django 6.0.1 on 2026-01-13 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="组织/公司"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="职位"
                    ),
                ),
                (
                    "email_notification",
                    models.BooleanField(default=True, verbose_name="邮件通知"),
                ),
                (
                    "sms_notification",
                    models.BooleanField(default=False, verbose_name="短信通知"),
                ),
                (
                    "webhook_notification",
                    models.BooleanField(default=False, verbose_name="Webhook通知"),
                ),
                (
                    "language",
                    models.CharField(
                        default="zh-hans", max_length=10, verbose_name="语言"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai", max_length=50, verbose_name="时区"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="light", max_length=20, verbose_name="主题"
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(default=20, verbose_name="每页显示数量"),
                ),
                (
                    "default_data_range",
                    models.CharField(
                        default="24h", max_length=20, verbose_name="默认数据范围"
                    ),
                ),
                (
                    "auto_refresh_interval",
                    models.IntegerField(default=30, verbose_name="自动刷新间隔(秒)"),
                ),
                (
                    "two_factor_enabled",
                    models.BooleanField(default=False, verbose_name="启用双因素认证"),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次修改密码时间"
                    ),
                ),
                (
                    "login_notification",
                    models.BooleanField(default=True, verbose_name="登录通知"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("create_device", "创建设备"),
                            ("update_device", "更新设备"),
                            ("delete_device", "删除设备"),
                            ("create_alert", "创建报警规则"),
                            ("acknowledge_alert", "确认报警"),
                            ("resolve_alert", "解决报警"),
                            ("export_data", "导出数据"),
                            ("change_settings", "修改设置"),
                        ],
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="操作描述")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户活动日志",
                "verbose_name_plural": "用户活动日志",
                "db_table": "user_activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="user_activi_user_id_543519_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="user_activi_action__1fe201_idx",
                    ),
                ],
            },
        ),
    ]
